/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demoui.stockui;

import java.awt.CardLayout;

/**
 *
 * @author administrasion
 */
public class cardPanel extends javax.swing.JPanel {
    CardLayout layout;
    GoodsManageUI goodsManageUI;
    /**
     * Creates new form cardPanel
     */
    public cardPanel() {
        initComponents();
        layout = (CardLayout)this.getLayout();
        goodsManageUI = new GoodsManageUI();
        this.add(goodsManageUI,"GoodsManageUI");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents

    public void change(String key){
        switch(key){
            case "GoodsManageUI": goodsManageUI = new GoodsManageUI();break;
        }
        layout.show(this, key);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
