/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demoui.stockui;

/**
 *
 * @author administrasion
 */
public class StockUI extends javax.swing.JPanel {

    /**
     * Creates new form StockUI
     */
    public StockUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new demoui.stockui.cardPanel();
        goodsManageButton = new javax.swing.JButton();
        viewStockButton = new javax.swing.JButton();
        stockCheckButton = new javax.swing.JButton();
        makeReceipt = new javax.swing.JButton();

        goodsManageButton.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        goodsManageButton.setText("商品管理");
        goodsManageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goodsManageButtonMousePressed(evt);
            }
        });

        viewStockButton.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        viewStockButton.setText("库存查看");
        viewStockButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewStockButtonMousePressed(evt);
            }
        });

        stockCheckButton.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        stockCheckButton.setText("库存盘点");
        stockCheckButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stockCheckButtonMousePressed(evt);
            }
        });

        makeReceipt.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        makeReceipt.setText("制定单据");
        makeReceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                makeReceiptMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goodsManageButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewStockButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stockCheckButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(makeReceipt, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(42, 42, 42)
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(goodsManageButton)
                .addGap(40, 40, 40)
                .addComponent(viewStockButton)
                .addGap(40, 40, 40)
                .addComponent(stockCheckButton)
                .addGap(40, 40, 40)
                .addComponent(makeReceipt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goodsManageButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goodsManageButtonMousePressed
        cardPanel.change("GoodsManageUI");
    }//GEN-LAST:event_goodsManageButtonMousePressed

    private void viewStockButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewStockButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewStockButtonMousePressed

    private void stockCheckButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockCheckButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockCheckButtonMousePressed

    private void makeReceiptMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makeReceiptMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_makeReceiptMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private demoui.stockui.cardPanel cardPanel;
    private javax.swing.JButton goodsManageButton;
    private javax.swing.JButton makeReceipt;
    private javax.swing.JButton stockCheckButton;
    private javax.swing.JButton viewStockButton;
    // End of variables declaration//GEN-END:variables
}
