/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demoui.salesui;

import businesslogicservice.saleblservice.SalesBLService;
import server.ClientStart;

/**
 *
 * @author HCW
 */
public class SalesReturnUI extends javax.swing.JPanel {

    /**
     * Creates new form SalesReturnUI
     */
    public SalesReturnUI() {
        initComponents();
        controller = ClientStart.getSalesBLService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salesListPanel = new demoui.salesui.SalesListPanel();
        salesReturnLable = new javax.swing.JLabel();
        salesListLable = new javax.swing.JLabel();
        viewSalesButton = new javax.swing.JButton();
        salesReturnButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));

        salesListPanel.setPreferredSize(new java.awt.Dimension(664, 442));

        salesReturnLable.setFont(new java.awt.Font("楷体", 0, 36)); // NOI18N
        salesReturnLable.setText("销售退货");

        salesListLable.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        salesListLable.setText("销售单列表：");

        viewSalesButton.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        viewSalesButton.setText("查看详情");

        salesReturnButton.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        salesReturnButton.setText("退货");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(salesReturnLable))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salesListLable)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(salesListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewSalesButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(salesReturnButton, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {salesReturnButton, viewSalesButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(salesReturnLable)
                .addGap(13, 13, 13)
                .addComponent(salesListLable)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(viewSalesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salesReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(salesListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {salesReturnButton, viewSalesButton});

    }// </editor-fold>//GEN-END:initComponents

    private SalesBLService controller;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel salesListLable;
    private demoui.salesui.SalesListPanel salesListPanel;
    private javax.swing.JButton salesReturnButton;
    private javax.swing.JLabel salesReturnLable;
    private javax.swing.JButton viewSalesButton;
    // End of variables declaration//GEN-END:variables
}
