/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demoui.salesui;

import businesslogicservice.saleblservice.SalesBLService;
import server.ClientStart;

/**
 *
 * @author HCW
 */
public class SalesUI extends javax.swing.JPanel {

    /**
     * Creates new form SalesUI
     */
    public SalesUI() {
        initComponents();
        controller = ClientStart.getSalesBLService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salesManager = new javax.swing.JLabel();
        clientLable = new javax.swing.JLabel();
        clientTextField = new javax.swing.JTextField();
        salesmanLable = new javax.swing.JLabel();
        salesmanTextField = new javax.swing.JTextField();
        clientAddButton = new javax.swing.JButton();
        clientRemoveButton = new javax.swing.JButton();
        storehouseLable = new javax.swing.JLabel();
        storehouseTextField = new javax.swing.JTextField();
        operatorLable = new javax.swing.JLabel();
        operatorTextField = new javax.swing.JTextField();
        totalLable = new javax.swing.JLabel();
        totalTextField = new javax.swing.JTextField();
        notesLable = new javax.swing.JLabel();
        notesTextField = new javax.swing.JTextField();
        salesListLable = new javax.swing.JLabel();
        salesGoodsScrollPane1 = new javax.swing.JScrollPane();
        salesGoodsTable = new javax.swing.JTable();
        giftGoodsLable = new javax.swing.JLabel();
        giftGoodsListjScrollPane2 = new javax.swing.JScrollPane();
        giftGoodsListTable = new javax.swing.JTable();
        goodsAdd = new javax.swing.JButton();
        deleteGoods = new javax.swing.JButton();
        beforeDiscountLable = new javax.swing.JLabel();
        beforeDiscountTextField = new javax.swing.JTextField();
        dicountLable = new javax.swing.JLabel();
        discountTextField = new javax.swing.JTextField();
        afterDiscountLable = new javax.swing.JLabel();
        afterDiscountTextField = new javax.swing.JTextField();
        sale = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));

        salesManager.setFont(new java.awt.Font("楷体", 0, 36)); // NOI18N
        salesManager.setText("销售管理");

        clientLable.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        clientLable.setText("客户：");

        salesmanLable.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        salesmanLable.setText("业务员：");

        salesmanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesmanTextFieldActionPerformed(evt);
            }
        });

        clientAddButton.setText("a");

        clientRemoveButton.setText("12");

        storehouseLable.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        storehouseLable.setText("仓库：");

        storehouseTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        operatorLable.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        operatorLable.setText("操作员：");

        totalLable.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        totalLable.setText("总额合计：");

        notesLable.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        notesLable.setText("备注：");

        salesListLable.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        salesListLable.setText("销售商品列表：");

        salesGoodsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        salesGoodsScrollPane1.setViewportView(salesGoodsTable);

        giftGoodsLable.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        giftGoodsLable.setText("赠品列表：");

        giftGoodsListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        giftGoodsListjScrollPane2.setViewportView(giftGoodsListTable);

        goodsAdd.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        goodsAdd.setText("添加商品");

        deleteGoods.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        deleteGoods.setText("删除商品");

        beforeDiscountLable.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        beforeDiscountLable.setText("折让前总额：");

        dicountLable.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        dicountLable.setText("折让：");

        discountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountTextFieldActionPerformed(evt);
            }
        });

        afterDiscountLable.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        afterDiscountLable.setText("折让后总额：");

        sale.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        sale.setText("确认销售");

        cancel.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        cancel.setText("取消销售");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(salesManager)
                .addGap(355, 355, 355))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dicountLable)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clientLable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clientAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clientRemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(salesmanLable)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(salesmanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(storehouseLable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(storehouseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(operatorLable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(operatorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(totalLable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(discountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(afterDiscountLable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(afterDiscountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(notesLable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(notesTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(giftGoodsLable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sale)
                                .addGap(18, 18, 18)
                                .addComponent(cancel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(beforeDiscountLable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(beforeDiscountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(salesListLable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(goodsAdd)
                                .addGap(18, 18, 18)
                                .addComponent(deleteGoods))
                            .addComponent(giftGoodsListjScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salesGoodsScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {clientAddButton, clientRemoveButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {afterDiscountTextField, beforeDiscountTextField, clientTextField, discountTextField, operatorTextField, salesmanTextField, storehouseTextField, totalTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(salesManager)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientLable)
                    .addComponent(clientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salesmanLable)
                    .addComponent(salesmanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientAddButton)
                    .addComponent(clientRemoveButton)
                    .addComponent(storehouseLable)
                    .addComponent(storehouseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operatorLable)
                    .addComponent(operatorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLable)
                    .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beforeDiscountLable)
                    .addComponent(beforeDiscountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dicountLable)
                    .addComponent(discountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(afterDiscountLable)
                    .addComponent(afterDiscountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(notesLable)
                            .addComponent(notesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salesListLable)
                            .addComponent(goodsAdd)
                            .addComponent(deleteGoods))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salesGoodsScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(giftGoodsLable)
                        .addGap(14, 14, 14)
                        .addComponent(giftGoodsListjScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancel)
                            .addComponent(sale))
                        .addGap(156, 156, 156))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {clientAddButton, clientRemoveButton});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {afterDiscountTextField, beforeDiscountTextField, clientTextField, discountTextField, operatorTextField, salesmanTextField, storehouseTextField, totalTextField});

    }// </editor-fold>//GEN-END:initComponents

    private void salesmanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesmanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salesmanTextFieldActionPerformed

    private void discountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountTextFieldActionPerformed


    private SalesBLService controller;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel afterDiscountLable;
    private javax.swing.JTextField afterDiscountTextField;
    private javax.swing.JLabel beforeDiscountLable;
    private javax.swing.JTextField beforeDiscountTextField;
    private javax.swing.JButton cancel;
    private javax.swing.JButton clientAddButton;
    private javax.swing.JLabel clientLable;
    private javax.swing.JButton clientRemoveButton;
    private javax.swing.JTextField clientTextField;
    private javax.swing.JButton deleteGoods;
    private javax.swing.JLabel dicountLable;
    private javax.swing.JTextField discountTextField;
    private javax.swing.JLabel giftGoodsLable;
    private javax.swing.JTable giftGoodsListTable;
    private javax.swing.JScrollPane giftGoodsListjScrollPane2;
    private javax.swing.JButton goodsAdd;
    private javax.swing.JLabel notesLable;
    private javax.swing.JTextField notesTextField;
    private javax.swing.JLabel operatorLable;
    private javax.swing.JTextField operatorTextField;
    private javax.swing.JButton sale;
    private javax.swing.JScrollPane salesGoodsScrollPane1;
    private javax.swing.JTable salesGoodsTable;
    private javax.swing.JLabel salesListLable;
    private javax.swing.JLabel salesManager;
    private javax.swing.JLabel salesmanLable;
    private javax.swing.JTextField salesmanTextField;
    private javax.swing.JLabel storehouseLable;
    private javax.swing.JTextField storehouseTextField;
    private javax.swing.JLabel totalLable;
    private javax.swing.JTextField totalTextField;
    // End of variables declaration//GEN-END:variables
}
