/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demoui.importui;

import businesslogicservice.importblservice.ImportBLService;
import server.ClientStart;

/**
 *
 * @author HCW
 */
public class ImportReturnUI extends javax.swing.JPanel {

    /**
     * Creates new form ImportReturnUI
     */
    public ImportReturnUI() {
        initComponents();
        controller = ClientStart.getImportBLService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        importListPanel = new demoui.importui.ImportListPanel();
        importReturnLable = new javax.swing.JLabel();
        importListLable = new javax.swing.JLabel();
        viewImportButton = new javax.swing.JButton();
        importReturnButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));

        importReturnLable.setFont(new java.awt.Font("楷体", 0, 36)); // NOI18N
        importReturnLable.setText("进货退货");

        importListLable.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        importListLable.setText("进货单列表：");

        viewImportButton.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        viewImportButton.setText("查看详情");

        importReturnButton.setFont(new java.awt.Font("楷体", 0, 12)); // NOI18N
        importReturnButton.setText("退货");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(328, Short.MAX_VALUE)
                .addComponent(importReturnLable)
                .addContainerGap(328, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(importListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewImportButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(importReturnButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(importListLable))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {importReturnButton, viewImportButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(importReturnLable)
                .addGap(13, 13, 13)
                .addComponent(importListLable)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(viewImportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(importReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(importListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {importReturnButton, viewImportButton});

    }// </editor-fold>//GEN-END:initComponents

    private ImportBLService controller;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel importListLable;
    private demoui.importui.ImportListPanel importListPanel;
    private javax.swing.JButton importReturnButton;
    private javax.swing.JLabel importReturnLable;
    private javax.swing.JButton viewImportButton;
    // End of variables declaration//GEN-END:variables
}
