/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demoui.financialui;
import businesslogicservice.financialblservice.AccountBLService;
import java.awt.Color;
import java.awt.Font;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import server.ClientStart;
import server.ServerInterface;
import utility.Tool;
import vo.AccountVO;
/**
 *
 * @author administrasion
 */
public class AccountUI extends javax.swing.JPanel {

    /**
     * Creates new form AccountUI
     */
    public AccountUI() {
        ClientStart.main();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addAccountDialog = new javax.swing.JDialog();
        nameLabel = new javax.swing.JLabel();
        accountNameLabel = new javax.swing.JLabel();
        accountBalanceLabel = new javax.swing.JLabel();
        accountNameTextField = new javax.swing.JTextField();
        accountBalanceTextField = new javax.swing.JTextField();
        addEnsureButton = new javax.swing.JButton();
        addCancelButton = new javax.swing.JButton();
        balanceHintLabel = new javax.swing.JLabel();
        nameHintLabel = new javax.swing.JLabel();
        functionLabel = new javax.swing.JLabel();
        delAccountButton = new javax.swing.JButton();
        findAccountButton = new javax.swing.JButton();
        addAccountButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ArrayList col = new ArrayList();
        col.add("账户名称");
        col.add("账户余额");
        accountTabel = new javax.swing.JTable();
        findTextField = new javax.swing.JTextField();

        addAccountDialog.setLocation(new java.awt.Point(200, 250));
        addAccountDialog.setMinimumSize(new java.awt.Dimension(400, 200));
        addAccountDialog.setSize(new java.awt.Dimension(400, 220));
        addAccountDialog.setLocationRelativeTo(null);

        nameLabel.setFont(Tool.getTitleFont());
        nameLabel.setText("添加账户");

        accountNameLabel.setFont(Tool.getButtonFont());
        accountNameLabel.setText("账户名：");

        accountBalanceLabel.setFont(Tool.getButtonFont());
        accountBalanceLabel.setText("账户余额：");

        accountNameTextField.setFont(Tool.getButtonFont());

        accountBalanceTextField.setFont(Tool.getButtonFont());

        addEnsureButton.setFont(Tool.getButtonFont());
        addEnsureButton.setText("确定");
        addEnsureButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addEnsureButtonMousePressed(evt);
            }
        });

        addCancelButton.setFont(Tool.getButtonFont());
        addCancelButton.setText("取消");
        addCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addCancelButtonMousePressed(evt);
            }
        });

        balanceHintLabel.setFont(Tool.getButtonFont());
        balanceHintLabel.setForeground(new java.awt.Color(255, 0, 0));

        nameHintLabel.setFont(Tool.getButtonFont());

        javax.swing.GroupLayout addAccountDialogLayout = new javax.swing.GroupLayout(addAccountDialog.getContentPane());
        addAccountDialog.getContentPane().setLayout(addAccountDialogLayout);
        addAccountDialogLayout.setHorizontalGroup(
            addAccountDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAccountDialogLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(addAccountDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountBalanceLabel)
                    .addComponent(accountNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addAccountDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accountNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(accountBalanceTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addAccountDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balanceHintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameHintLabel))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(addAccountDialogLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(addEnsureButton)
                .addGap(59, 59, 59)
                .addComponent(addCancelButton)
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addAccountDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addAccountDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {balanceHintLabel, nameHintLabel});

        addAccountDialogLayout.setVerticalGroup(
            addAccountDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAccountDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(addAccountDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNameLabel)
                    .addComponent(accountNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameHintLabel))
                .addGap(19, 19, 19)
                .addGroup(addAccountDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balanceHintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addAccountDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(accountBalanceLabel)
                        .addComponent(accountBalanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(addAccountDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEnsureButton)
                    .addComponent(addCancelButton))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        addAccountDialogLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {accountBalanceTextField, balanceHintLabel, nameHintLabel});

        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        functionLabel.setFont(new java.awt.Font("楷体", 0, 36)); // NOI18N
        functionLabel.setText("帐户管理");

        delAccountButton.setFont(addAccountButton.getFont());
        delAccountButton.setText("删除账户");
        delAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                delAccountButtonMousePressed(evt);
            }
        });

        findAccountButton.setFont(addAccountButton.getFont());
        findAccountButton.setText("查找账户");
        findAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                findAccountButtonMousePressed(evt);
            }
        });

        addAccountButton.setFont(new java.awt.Font("楷体", 0, 16)); // NOI18N
        addAccountButton.setText("添加帐户");
        addAccountButton.setMaximumSize(new java.awt.Dimension(111, 35));
        addAccountButton.setMinimumSize(new java.awt.Dimension(111, 35));
        addAccountButton.setPreferredSize(new java.awt.Dimension(111, 35));
        addAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addAccountButtonMousePressed(evt);
            }
        });

        accountTabel.setAutoCreateRowSorter(true);
        accountTabel.setModel(new AccountTableModel(getData(),col));
        accountTabel.setPreferredSize(new java.awt.Dimension(660, 330));
        accountTabel.setSize(new java.awt.Dimension(660, 330));
        jScrollPane1.setViewportView(accountTabel);
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        accountTabel.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(functionLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(addAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(delAccountButton)
                .addGap(18, 18, 18)
                .addComponent(findTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(findAccountButton)
                .addGap(15, 15, 15))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addAccountButton, delAccountButton, findAccountButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(functionLabel)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delAccountButton)
                    .addComponent(findAccountButton)
                    .addComponent(addAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addAccountButton, delAccountButton, findAccountButton});

    }// </editor-fold>//GEN-END:initComponents

    private void addAccountButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAccountButtonMousePressed
        addAccountDialog.setVisible(true);
    }//GEN-LAST:event_addAccountButtonMousePressed

    private void addEnsureButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEnsureButtonMousePressed
        
        if(accountNameTextField.getText().equals("")){
            nameHintLabel.setText("输入不能为空");
            return;
        }else{
            nameHintLabel.setText("");
        }
        
        if(accountBalanceTextField.getText().equals("")){
            balanceHintLabel.setText("输入不能为空");
            return;
        }else{
            balanceHintLabel.setText("");
        }
        
        if(!Tool.isNumeric(accountBalanceTextField.getText())){
            balanceHintLabel.setText("请输入有效的数字");
            return;
        }else{
            balanceHintLabel.setText("");
        }
      
        ((AccountTableModel)accountTabel.getModel()).addRow(accountNameTextField.getText(), Double.parseDouble(accountBalanceTextField.getText()));
        accountNameTextField.setText("");
        accountBalanceTextField.setText("");
        addAccountDialog.setVisible(false);
    }//GEN-LAST:event_addEnsureButtonMousePressed

    private void delAccountButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delAccountButtonMousePressed
        int rows[] = accountTabel.getSelectedRows();
        for(int row : rows){
            ((AccountTableModel)accountTabel.getModel()).removeRow(accountTabel.convertRowIndexToModel(row));
        }
    }//GEN-LAST:event_delAccountButtonMousePressed

    private void addCancelButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCancelButtonMousePressed
        addAccountDialog.setVisible(false);
    }//GEN-LAST:event_addCancelButtonMousePressed

    private void findAccountButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findAccountButtonMousePressed
        int index = ((AccountTableModel)accountTabel.getModel()).getIndexOf(findTextField.getText());
        index = accountTabel.convertRowIndexToView(index);
        if(index != -1){
            accountTabel.setRowSelectionInterval(index, index);
        }else{
            JOptionPane.showMessageDialog(this, "未找到");
            return;
        }
    }//GEN-LAST:event_findAccountButtonMousePressed

    private ArrayList<AccountVO> getData(){
        try{
            ServerInterface serverInterface = ClientStart.server;
            if(serverInterface != null){
                AccountBLService accountBLService = serverInterface.getAccountBLService();
                return accountBLService.getList();
            }else{
                return new ArrayList<AccountVO>();
            }
        } catch (RemoteException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        return null;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountBalanceLabel;
    private javax.swing.JTextField accountBalanceTextField;
    private javax.swing.JLabel accountNameLabel;
    private javax.swing.JTextField accountNameTextField;
    private javax.swing.JTable accountTabel;
    private javax.swing.JButton addAccountButton;
    private javax.swing.JDialog addAccountDialog;
    private javax.swing.JButton addCancelButton;
    private javax.swing.JButton addEnsureButton;
    private javax.swing.JLabel balanceHintLabel;
    private javax.swing.JButton delAccountButton;
    private javax.swing.JButton findAccountButton;
    private javax.swing.JTextField findTextField;
    private javax.swing.JLabel functionLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameHintLabel;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
