/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demoui.financialui;

import java.awt.CardLayout;

/**
 *
 * @author administrasion
 */
public class cardPanel extends javax.swing.JPanel {

    /**
     * Creates new form cardPanel
     */
    public CardLayout layout;
    AccountUI accountUI;
    ReceiptUI receiptUI;
    public cardPanel() {
        initComponents();
        layout = (CardLayout)this.getLayout();
        accountUI = new AccountUI();
        receiptUI = new ReceiptUI();
        this.add(accountUI,"AccountUI");
        this.add(receiptUI,"ReceiptUI");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents

    public void change(String key){
        switch(key){
            case "AccountUI": accountUI = new AccountUI();break;
            case "ReceiptUI": receiptUI = new ReceiptUI();break;
        }
        layout.show(this, key);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
