/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demoui.financialui;

/**
 *
 * @author administrasion
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountManageButton = new javax.swing.JButton();
        makeReceiptButton = new javax.swing.JButton();
        viewReportButton = new javax.swing.JButton();
        buildNewRecordButton = new javax.swing.JButton();
        cardPanel = new demoui.financialui.cardPanel();

        accountManageButton.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        accountManageButton.setText("账户管理");
        accountManageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accountManageButtonMousePressed(evt);
            }
        });

        makeReceiptButton.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        makeReceiptButton.setText("制定单据");
        makeReceiptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                makeReceiptButtonMousePressed(evt);
            }
        });

        viewReportButton.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        viewReportButton.setText("查看报表");

        buildNewRecordButton.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        buildNewRecordButton.setText("建立新账");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buildNewRecordButton)
                    .addComponent(viewReportButton)
                    .addComponent(makeReceiptButton)
                    .addComponent(accountManageButton))
                .addGap(18, 18, 18)
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(accountManageButton)
                .addGap(40, 40, 40)
                .addComponent(makeReceiptButton)
                .addGap(40, 40, 40)
                .addComponent(viewReportButton)
                .addGap(40, 40, 40)
                .addComponent(buildNewRecordButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accountManageButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountManageButtonMousePressed
        cardPanel.change("AccountUI");
    }//GEN-LAST:event_accountManageButtonMousePressed

    private void makeReceiptButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makeReceiptButtonMousePressed
        cardPanel.change("ReceiptUI");
    }//GEN-LAST:event_makeReceiptButtonMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountManageButton;
    private javax.swing.JButton buildNewRecordButton;
    private demoui.financialui.cardPanel cardPanel;
    private javax.swing.JButton makeReceiptButton;
    private javax.swing.JButton viewReportButton;
    // End of variables declaration//GEN-END:variables
}
