/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demoui.financialui;
import businesslogicservice.financialblservice.AccountBLService;
import businesslogicservice.financialblservice.CashRecordBLService;
import businesslogicservice.financialblservice.MoneyBLService;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import server.ClientStart;
import server.ServerInterface;
import utility.MyTableModel;
import utility.Tool;
import vo.AccountVO;
import vo.FinancialReceiptLineItemVO;
import vo.MoneyLineItemVO;
import vo.MoneyVO;
import vo.ReceiptType;
/**
 *
 * @author administrasion
 */
public class ReceiptUI extends javax.swing.JPanel {
    MoneyBLService moneyBLService;
    CashRecordBLService cashRecordBLService;
    /**
     * Creates new form AccountUI
     */
    public ReceiptUI() {
        initComponents();
        moneyBLService = ClientStart.getMoneyBLService(type);
        cashRecordBLService = ClientStart.getCashRecordBLService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMoneyReceiptDialog = new javax.swing.JDialog();
        nameLabel = new javax.swing.JLabel();
        title1Label = new javax.swing.JLabel();
        moneyClientLabel = new javax.swing.JLabel();
        moneyClientTextField = new javax.swing.JTextField();
        addMoneyEnsureButton = new javax.swing.JButton();
        addMoneyCancelButton = new javax.swing.JButton();
        clientNameHintLabel = new javax.swing.JLabel();
        moneySerialNumberLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        moneySumLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        moneyItemTable = new javax.swing.JTable();
        moneyAddItemButton = new javax.swing.JButton();
        moneyDelItemButton = new javax.swing.JButton();
        addMoneyItemDialog = new javax.swing.JDialog();
        nameLabel1 = new javax.swing.JLabel();
        itemAccountTitile = new javax.swing.JLabel();
        moneyItemAccountTextField = new javax.swing.JTextField();
        moneyItemSumTextField = new javax.swing.JTextField();
        itemSumTitile = new javax.swing.JLabel();
        moneyItemCommentTextField = new javax.swing.JTextField();
        itemCommentTitile = new javax.swing.JLabel();
        addMoneyItemEnsureButton = new javax.swing.JButton();
        addMoneyItemCancelButton = new javax.swing.JButton();
        moneyItemSumHint = new javax.swing.JLabel();
        moneyItemAccountHintLabel = new javax.swing.JLabel();
        addCashRecordReceiptDialog = new javax.swing.JDialog();
        nameLabel2 = new javax.swing.JLabel();
        title1Label1 = new javax.swing.JLabel();
        clientLabel1 = new javax.swing.JLabel();
        cashRecordAccountName = new javax.swing.JTextField();
        addCashRecordEnsureButton = new javax.swing.JButton();
        addCashRecordCancelButton = new javax.swing.JButton();
        cashRecordAccountHintLabel = new javax.swing.JLabel();
        clientNameHintLabel1 = new javax.swing.JLabel();
        cashRecordSerialNumberLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cashRecordSumLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cashRecordItemTable = new javax.swing.JTable();
        cashRecordAddItemButton = new javax.swing.JButton();
        cashRecordDelItemButton = new javax.swing.JButton();
        addCashRecordItemDialog = new javax.swing.JDialog();
        nameLabel3 = new javax.swing.JLabel();
        CashRecordItemName = new javax.swing.JLabel();
        cashRecordItemNameTextField = new javax.swing.JTextField();
        cashRecordItemSumTextField = new javax.swing.JTextField();
        itemSumTitile1 = new javax.swing.JLabel();
        cashRecordItemCommentTextField = new javax.swing.JTextField();
        itemCommentTitile1 = new javax.swing.JLabel();
        addCashRecordItemEnsureButton = new javax.swing.JButton();
        addCashRecordItemCancelButton = new javax.swing.JButton();
        cashRecordItemSumHint = new javax.swing.JLabel();
        functionLabel = new javax.swing.JLabel();
        findAccountButton = new javax.swing.JButton();
        addReceiptButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        receiptTabel = new javax.swing.JTable();
        typeComboBox = new javax.swing.JComboBox();
        findTextField = new javax.swing.JTextField();

        addMoneyReceiptDialog.setLocation(new java.awt.Point(300, 400));
        addMoneyReceiptDialog.setMinimumSize(new java.awt.Dimension(400, 188));

        nameLabel.setFont(new java.awt.Font("KaiTi", 0, 24)); // NOI18N
        nameLabel.setText("添加收付款单");

        title1Label.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        title1Label.setText("单据编号：");

        moneyClientLabel.setFont(title1Label.getFont());
        moneyClientLabel.setText("客户名：");

        addMoneyEnsureButton.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        addMoneyEnsureButton.setText("确定");
        addMoneyEnsureButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addMoneyEnsureButtonMousePressed(evt);
            }
        });

        addMoneyCancelButton.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        addMoneyCancelButton.setText("取消");
        addMoneyCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addMoneyCancelButtonMousePressed(evt);
            }
        });

        moneySerialNumberLabel.setFont(title1Label.getFont());

        jLabel1.setFont(title1Label.getFont());
        jLabel1.setText("总额汇总：");

        moneySumLabel.setFont(title1Label.getFont());

        moneyItemTable.setModel(new demoui.financialui.FinancialReceiptItemTableModel(new ArrayList<FinancialReceiptLineItemVO>(),getItemCol(),getReceiptType()));
        jScrollPane2.setViewportView(moneyItemTable);

        moneyAddItemButton.setFont(addMoneyEnsureButton.getFont());
        moneyAddItemButton.setText("添加条目");
        moneyAddItemButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moneyAddItemButtonMousePressed(evt);
            }
        });
        moneyAddItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyAddItemButtonActionPerformed(evt);
            }
        });

        moneyDelItemButton.setFont(addMoneyEnsureButton.getFont());
        moneyDelItemButton.setText("删除条目");
        moneyDelItemButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moneyDelItemButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout addMoneyReceiptDialogLayout = new javax.swing.GroupLayout(addMoneyReceiptDialog.getContentPane());
        addMoneyReceiptDialog.getContentPane().setLayout(addMoneyReceiptDialogLayout);
        addMoneyReceiptDialogLayout.setHorizontalGroup(
            addMoneyReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMoneyReceiptDialogLayout.createSequentialGroup()
                .addGroup(addMoneyReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addMoneyReceiptDialogLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addMoneyReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title1Label)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addMoneyReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addMoneyReceiptDialogLayout.createSequentialGroup()
                                .addComponent(moneySerialNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moneyClientLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moneyClientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clientNameHintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addMoneyReceiptDialogLayout.createSequentialGroup()
                                .addGroup(addMoneyReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(moneyAddItemButton)
                                    .addComponent(moneySumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(110, 110, 110)
                                .addComponent(moneyDelItemButton))))
                    .addGroup(addMoneyReceiptDialogLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(addMoneyEnsureButton)
                        .addGap(178, 178, 178)
                        .addComponent(addMoneyCancelButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(addMoneyReceiptDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addMoneyReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addMoneyReceiptDialogLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(nameLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addMoneyReceiptDialogLayout.setVerticalGroup(
            addMoneyReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMoneyReceiptDialogLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(addMoneyReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientNameHintLabel)
                    .addComponent(moneySerialNumberLabel)
                    .addComponent(title1Label)
                    .addGroup(addMoneyReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(moneyClientLabel)
                        .addComponent(moneyClientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(addMoneyReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(moneySumLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(addMoneyReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moneyDelItemButton)
                    .addComponent(moneyAddItemButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addMoneyReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMoneyEnsureButton)
                    .addComponent(addMoneyCancelButton)))
        );

        addMoneyReceiptDialogLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {clientNameHintLabel, moneyClientTextField});

        addMoneyReceiptDialogLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {moneySerialNumberLabel, title1Label});

        addMoneyReceiptDialogLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, moneySumLabel});

        nameLabel1.setFont(new java.awt.Font("KaiTi", 0, 24)); // NOI18N
        nameLabel1.setText("添加条目");

        itemAccountTitile.setFont(title1Label.getFont());
        itemAccountTitile.setText("银行账户：");

        itemSumTitile.setFont(title1Label.getFont());
        itemSumTitile.setText("金额：");

        itemCommentTitile.setFont(title1Label.getFont());
        itemCommentTitile.setText("备注：");

        addMoneyItemEnsureButton.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        addMoneyItemEnsureButton.setText("确定");
        addMoneyItemEnsureButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addMoneyItemEnsureButtonMousePressed(evt);
            }
        });

        addMoneyItemCancelButton.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        addMoneyItemCancelButton.setText("取消");
        addMoneyItemCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addMoneyItemCancelButtonMousePressed(evt);
            }
        });

        moneyItemAccountHintLabel.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        moneyItemAccountHintLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout addMoneyItemDialogLayout = new javax.swing.GroupLayout(addMoneyItemDialog.getContentPane());
        addMoneyItemDialog.getContentPane().setLayout(addMoneyItemDialogLayout);
        addMoneyItemDialogLayout.setHorizontalGroup(
            addMoneyItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMoneyItemDialogLayout.createSequentialGroup()
                .addGroup(addMoneyItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addMoneyItemDialogLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(addMoneyItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(addMoneyItemDialogLayout.createSequentialGroup()
                                .addComponent(itemCommentTitile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(moneyItemCommentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addMoneyItemDialogLayout.createSequentialGroup()
                                .addGroup(addMoneyItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemAccountTitile)
                                    .addComponent(itemSumTitile))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addMoneyItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(moneyItemSumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(moneyItemAccountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addMoneyItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moneyItemSumHint, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(moneyItemAccountHintLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(addMoneyItemDialogLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(addMoneyItemEnsureButton)
                        .addGap(52, 52, 52)
                        .addComponent(addMoneyItemCancelButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(addMoneyItemDialogLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(nameLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addMoneyItemDialogLayout.setVerticalGroup(
            addMoneyItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMoneyItemDialogLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nameLabel1)
                .addGap(18, 18, 18)
                .addGroup(addMoneyItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moneyItemAccountHintLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addMoneyItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(itemAccountTitile)
                        .addComponent(moneyItemAccountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addMoneyItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moneyItemSumHint, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addMoneyItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(itemSumTitile)
                        .addComponent(moneyItemSumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addMoneyItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemCommentTitile)
                    .addComponent(moneyItemCommentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(addMoneyItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMoneyItemEnsureButton)
                    .addComponent(addMoneyItemCancelButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        addMoneyItemDialogLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {itemSumTitile, moneyItemSumHint});

        addMoneyItemDialogLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {itemAccountTitile, moneyItemAccountHintLabel});

        addCashRecordReceiptDialog.setLocation(new java.awt.Point(300, 400));
        addCashRecordReceiptDialog.setMinimumSize(new java.awt.Dimension(400, 188));

        nameLabel2.setFont(new java.awt.Font("KaiTi", 0, 24)); // NOI18N
        nameLabel2.setText("添加现金费用单");

        title1Label1.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        title1Label1.setText("单据编号：");

        clientLabel1.setFont(title1Label.getFont());
        clientLabel1.setText("账户名：");

        cashRecordAccountName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashRecordAccountNameActionPerformed(evt);
            }
        });

        addCashRecordEnsureButton.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        addCashRecordEnsureButton.setText("确定");
        addCashRecordEnsureButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addCashRecordEnsureButtonMousePressed(evt);
            }
        });

        addCashRecordCancelButton.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        addCashRecordCancelButton.setText("取消");
        addCashRecordCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addCashRecordCancelButtonMousePressed(evt);
            }
        });

        cashRecordAccountHintLabel.setForeground(new java.awt.Color(255, 0, 0));

        try{
            moneySerialNumberLabel.setText(moneyBLService.getSerialNumber());
        }catch(Exception e){
            e.printStackTrace();
        }
        cashRecordSerialNumberLabel.setFont(title1Label.getFont());

        jLabel3.setFont(title1Label.getFont());
        jLabel3.setText("总额汇总：");

        cashRecordSumLabel.setFont(title1Label.getFont());

        cashRecordItemTable.setModel(new demoui.financialui.FinancialReceiptItemTableModel(new ArrayList<FinancialReceiptLineItemVO>(), getItemCol(), type));
        jScrollPane3.setViewportView(cashRecordItemTable);

        cashRecordAddItemButton.setFont(addMoneyEnsureButton.getFont());
        cashRecordAddItemButton.setText("添加条目");
        cashRecordAddItemButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cashRecordAddItemButtonMousePressed(evt);
            }
        });

        cashRecordDelItemButton.setFont(addMoneyEnsureButton.getFont());
        cashRecordDelItemButton.setText("删除条目");
        cashRecordDelItemButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cashRecordDelItemButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout addCashRecordReceiptDialogLayout = new javax.swing.GroupLayout(addCashRecordReceiptDialog.getContentPane());
        addCashRecordReceiptDialog.getContentPane().setLayout(addCashRecordReceiptDialogLayout);
        addCashRecordReceiptDialogLayout.setHorizontalGroup(
            addCashRecordReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCashRecordReceiptDialogLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(nameLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(addCashRecordReceiptDialogLayout.createSequentialGroup()
                .addGroup(addCashRecordReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCashRecordReceiptDialogLayout.createSequentialGroup()
                        .addGroup(addCashRecordReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addCashRecordReceiptDialogLayout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(addCashRecordEnsureButton)
                                .addGap(159, 159, 159)
                                .addComponent(addCashRecordCancelButton))
                            .addGroup(addCashRecordReceiptDialogLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCashRecordReceiptDialogLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addCashRecordReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title1Label1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addCashRecordReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addCashRecordReceiptDialogLayout.createSequentialGroup()
                                .addComponent(cashRecordSerialNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clientLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cashRecordAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addCashRecordReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clientNameHintLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cashRecordAccountHintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(addCashRecordReceiptDialogLayout.createSequentialGroup()
                                .addGroup(addCashRecordReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cashRecordAddItemButton)
                                    .addComponent(cashRecordSumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(110, 110, 110)
                                .addComponent(cashRecordDelItemButton)))
                        .addGap(104, 104, 104)))
                .addContainerGap())
        );
        addCashRecordReceiptDialogLayout.setVerticalGroup(
            addCashRecordReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCashRecordReceiptDialogLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(nameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCashRecordReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addCashRecordReceiptDialogLayout.createSequentialGroup()
                        .addComponent(clientNameHintLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cashRecordAccountHintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addCashRecordReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clientLabel1)
                        .addComponent(cashRecordAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cashRecordSerialNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title1Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(addCashRecordReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cashRecordSumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(addCashRecordReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashRecordDelItemButton)
                    .addComponent(cashRecordAddItemButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addCashRecordReceiptDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCashRecordEnsureButton)
                    .addComponent(addCashRecordCancelButton)))
        );

        addCashRecordReceiptDialogLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cashRecordSerialNumberLabel, title1Label1});

        addCashRecordReceiptDialogLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cashRecordSumLabel, jLabel3});

        nameLabel3.setFont(new java.awt.Font("KaiTi", 0, 24)); // NOI18N
        nameLabel3.setText("添加条目");

        CashRecordItemName.setFont(title1Label.getFont());
        CashRecordItemName.setText("条目名：");

        cashRecordItemNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashRecordItemNameTextFieldActionPerformed(evt);
            }
        });

        cashRecordItemSumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashRecordItemSumTextFieldActionPerformed(evt);
            }
        });

        itemSumTitile1.setFont(title1Label.getFont());
        itemSumTitile1.setText("金额：");

        cashRecordItemCommentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashRecordItemCommentTextFieldActionPerformed(evt);
            }
        });

        itemCommentTitile1.setFont(title1Label.getFont());
        itemCommentTitile1.setText("备注：");

        addCashRecordItemEnsureButton.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        addCashRecordItemEnsureButton.setText("确定");
        addCashRecordItemEnsureButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addCashRecordItemEnsureButtonMousePressed(evt);
            }
        });

        addCashRecordItemCancelButton.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        addCashRecordItemCancelButton.setText("取消");
        addCashRecordItemCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addCashRecordItemCancelButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout addCashRecordItemDialogLayout = new javax.swing.GroupLayout(addCashRecordItemDialog.getContentPane());
        addCashRecordItemDialog.getContentPane().setLayout(addCashRecordItemDialogLayout);
        addCashRecordItemDialogLayout.setHorizontalGroup(
            addCashRecordItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCashRecordItemDialogLayout.createSequentialGroup()
                .addGroup(addCashRecordItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCashRecordItemDialogLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(addCashRecordItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(addCashRecordItemDialogLayout.createSequentialGroup()
                                .addComponent(itemCommentTitile1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cashRecordItemCommentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addCashRecordItemDialogLayout.createSequentialGroup()
                                .addGroup(addCashRecordItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CashRecordItemName)
                                    .addComponent(itemSumTitile1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addCashRecordItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cashRecordItemSumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cashRecordItemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cashRecordItemSumHint, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(addCashRecordItemDialogLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(addCashRecordItemEnsureButton)
                        .addGap(52, 52, 52)
                        .addComponent(addCashRecordItemCancelButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(addCashRecordItemDialogLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(nameLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addCashRecordItemDialogLayout.setVerticalGroup(
            addCashRecordItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCashRecordItemDialogLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nameLabel3)
                .addGap(18, 18, 18)
                .addGroup(addCashRecordItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CashRecordItemName)
                    .addComponent(cashRecordItemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addCashRecordItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashRecordItemSumHint, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addCashRecordItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(itemSumTitile1)
                        .addComponent(cashRecordItemSumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addCashRecordItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemCommentTitile1)
                    .addComponent(cashRecordItemCommentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(addCashRecordItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCashRecordItemEnsureButton)
                    .addComponent(addCashRecordItemCancelButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        addCashRecordItemDialogLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cashRecordItemSumHint, itemSumTitile1});

        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        functionLabel.setFont(new java.awt.Font("楷体", 0, 36)); // NOI18N
        functionLabel.setText("制定单据");

        findAccountButton.setFont(addReceiptButton.getFont());
        findAccountButton.setText("查找单据");
        findAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                findAccountButtonMousePressed(evt);
            }
        });
        findAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findAccountButtonActionPerformed(evt);
            }
        });

        addReceiptButton.setFont(new java.awt.Font("楷体", 0, 16)); // NOI18N
        addReceiptButton.setText("添加单据");
        addReceiptButton.setMaximumSize(new java.awt.Dimension(111, 35));
        addReceiptButton.setMinimumSize(new java.awt.Dimension(111, 35));
        addReceiptButton.setPreferredSize(new java.awt.Dimension(111, 35));
        addReceiptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addReceiptButtonMousePressed(evt);
            }
        });

        receiptTabel.setModel(new MyTableModel(new Vector(),getMoneyCol()));
        receiptTabel.setColumnSelectionAllowed(true);
        receiptTabel.setPreferredSize(new java.awt.Dimension(660, 330));
        receiptTabel.setSize(new java.awt.Dimension(660, 330));
        jScrollPane1.setViewportView(receiptTabel);
        receiptTabel.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        typeComboBox.setFont(addReceiptButton.getFont());
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "收款单", "付款单", "现金费用单" }));
        typeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeComboBoxItemStateChanged(evt);
            }
        });

        findTextField.setFont(new java.awt.Font("KaiTi", 0, 16)); // NOI18N
        findTextField.setForeground(new java.awt.Color(102, 102, 102));
        findTextField.setText("请输入单据编号");
        findTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                findTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                findTextFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(addReceiptButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(findTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(findAccountButton)
                        .addGap(15, 15, 15))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(functionLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addReceiptButton, findAccountButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(functionLabel)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findAccountButton)
                    .addComponent(addReceiptButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addReceiptButton, findAccountButton});

    }// </editor-fold>//GEN-END:initComponents

    
    private void addReceiptButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addReceiptButtonMousePressed
        if(type != ReceiptType.CashRecord){
            moneyBLService = ClientStart.getMoneyBLService(this.type);//建立一次新操作
            try {
                moneySerialNumberLabel.setText(moneyBLService.getSerialNumber());
            } catch (RemoteException ex) {
                Logger.getLogger(ReceiptUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            addMoneyReceiptDialog.setVisible(true);
        }else{
            cashRecordBLService = ClientStart.getCashRecordBLService();
            try {
                cashRecordSerialNumberLabel.setText(cashRecordBLService.getSerialNumber());
            } catch (RemoteException ex) {
                Logger.getLogger(ReceiptUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            addCashRecordReceiptDialog.setVisible(true);
        }
    }//GEN-LAST:event_addReceiptButtonMousePressed

    private void addMoneyEnsureButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMoneyEnsureButtonMousePressed

        if(moneyClientTextField.getText().equals("")){
            clientNameHintLabel.setText("输入不能为空");
            return;
        }else{
            clientNameHintLabel.setText("");
        }

        try {
            moneyBLService.finish();
        } catch (RemoteException ex) {
            Logger.getLogger(ReceiptUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        moneyClientTextField.setText("");
        clientNameHintLabel.setText("");
        
        Vector line = new Vector();
        line.add(moneySerialNumberLabel.getText());
        line.add(moneyClientTextField.getText());
        line.add();//用户名
        line.add(Double.parseDouble(moneySumLabel.getText()));
        
        ((MyTableModel)receiptTabel.getModel()).addRow(line);
        addMoneyReceiptDialog.setVisible(false);
        
    }//GEN-LAST:event_addMoneyEnsureButtonMousePressed

    private void addMoneyItemEnsureButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMoneyItemEnsureButtonMousePressed
        double sum = 0;
         if(Tool.isNumeric(moneyItemSumTextField.getText())){
            sum = Double.parseDouble(moneyItemSumTextField.getText());
            moneyItemSumHint.setText("");
        }else{
            moneyItemSumHint.setText("请输入有效的数字");
            return;
        }
        
        AccountBLService accountBLService = ClientStart.getAccountBLService();
        AccountVO accountVO = null;
        try {
            accountVO = accountBLService.findAccount(moneyItemAccountTextField.getText());
        } catch (RemoteException ex) {
            Logger.getLogger(ReceiptUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(accountVO == null){
            moneyItemAccountHintLabel.setText("不存在该账户");
            return;
        }else if(accountVO.getBalance() < sum){
            moneyItemAccountHintLabel.setText("没钱了！");
        }else{
            moneyItemAccountHintLabel.setText("");
        }
        
        ((FinancialReceiptItemTableModel)moneyItemTable.getModel()).addRow(moneyItemAccountTextField.getText(), sum, moneyItemCommentTextField.getText());
        try {
            moneyBLService.addItem(new MoneyLineItemVO(moneyItemAccountTextField.getText(), sum, moneyItemCommentTextField.getText()));
            moneySumLabel.setText(moneyBLService.getSum() + "");
        } catch (RemoteException ex) {
            Logger.getLogger(ReceiptUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        addMoneyItemDialog.setVisible(false);
    }//GEN-LAST:event_addMoneyItemEnsureButtonMousePressed

    private void addMoneyItemCancelButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMoneyItemCancelButtonMousePressed
        moneyItemAccountTextField.setText("");
        moneyItemSumTextField.setText("");
        moneyItemCommentTextField.setText("");
        moneyItemAccountHintLabel.setText("");
        moneyItemSumHint.setText("");
        addMoneyItemDialog.setVisible(false);
    }//GEN-LAST:event_addMoneyItemCancelButtonMousePressed

    private void addMoneyCancelButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMoneyCancelButtonMousePressed
        clientNameHintLabel.setText("");
        moneyClientTextField.setText("");
        addMoneyReceiptDialog.setVisible(false);
    }//GEN-LAST:event_addMoneyCancelButtonMousePressed

    private void moneyAddItemButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moneyAddItemButtonMousePressed
        addMoneyItemDialog.setVisible(true);
    }//GEN-LAST:event_moneyAddItemButtonMousePressed

    private void moneyDelItemButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moneyDelItemButtonMousePressed
        FinancialReceiptItemTableModel model = (FinancialReceiptItemTableModel)moneyItemTable.getModel();
        for(int row : moneyItemTable.getSelectedRows()){
            model.removeRow(row);
        }
    }//GEN-LAST:event_moneyDelItemButtonMousePressed

    private void moneyAddItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyAddItemButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyAddItemButtonActionPerformed

    private void typeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeComboBoxItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
           String type = (String)typeComboBox.getSelectedItem();
            switch(type){
                case "收款单":this.type = ReceiptType.Receive;
                receiptTabel.setModel(new MyTableModel(new Vector(), getMoneyCol()));
                break;
                case "付款单":this.type = ReceiptType.Pay;
                receiptTabel.setModel(new MyTableModel(new Vector(), getMoneyCol()));
                break;
                case "现金费用单":this.type = ReceiptType.CashRecord;
                receiptTabel.setModel(new MyTableModel(new Vector(), getCashRecordCol()));
                break;
            }
            receiptTabel.setModel(new FinancialReceiptItemTableModel(new ArrayList<FinancialReceiptLineItemVO>(), getItemCol(), this.type));
        }
    }//GEN-LAST:event_typeComboBoxItemStateChanged

    private void findAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findAccountButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findAccountButtonActionPerformed

    private void cashRecordAccountNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashRecordAccountNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashRecordAccountNameActionPerformed

    private void addCashRecordEnsureButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCashRecordEnsureButtonMousePressed
        if(cashRecordAccountName.getText().equals("")){
            cashRecordAccountHintLabel.setText("输入不能为空");
            return;
        }else{
            AccountBLService accountBLService = ClientStart.getAccountBLService();
            try {
                if(accountBLService.findAccount(cashRecordAccountName.getText()) != null){
                    clientNameHintLabel.setText("不存在该账户");
                    return;
                }else{
                    clientNameHintLabel.setText("");
                }
            } catch (RemoteException ex) {
                Logger.getLogger(ReceiptUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        try {
            cashRecordBLService.finish();
        } catch (RemoteException ex) {
            Logger.getLogger(ReceiptUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        cashRecordAccountName.setText("");
        cashRecordAccountHintLabel.setText("");
        
        Vector line = new Vector();
        line.add(cashRecordSerialNumberLabel.getText());
        line.add();//用户名
        line.add(cashRecordAccountName.getText());
        line.add(Double.parseDouble(cashRecordSumLabel.getText()));
        
        ((MyTableModel)receiptTabel.getModel()).addRow(line);
        addMoneyReceiptDialog.setVisible(false);
        
    }//GEN-LAST:event_addCashRecordEnsureButtonMousePressed

    private void addCashRecordCancelButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCashRecordCancelButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCashRecordCancelButtonMousePressed

    private void cashRecordAddItemButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashRecordAddItemButtonMousePressed
        addCashRecordItemDialog.setVisible(true);
    }//GEN-LAST:event_cashRecordAddItemButtonMousePressed

    private void cashRecordDelItemButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashRecordDelItemButtonMousePressed
        FinancialReceiptItemTableModel model = (FinancialReceiptItemTableModel)cashRecordItemTable.getModel();
        for(int row : cashRecordItemTable.getSelectedRows()){
            model.removeRow(row);
        }
    }//GEN-LAST:event_cashRecordDelItemButtonMousePressed

    private void cashRecordItemNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashRecordItemNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashRecordItemNameTextFieldActionPerformed

    private void cashRecordItemSumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashRecordItemSumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashRecordItemSumTextFieldActionPerformed

    private void cashRecordItemCommentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashRecordItemCommentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashRecordItemCommentTextFieldActionPerformed

    private void addCashRecordItemEnsureButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCashRecordItemEnsureButtonMousePressed
        if(Tool.isNumeric(cashRecordItemSumTextField.getText())){
            try {
                MoneyLineItemVO moneyLineItemVO = new MoneyLineItemVO(moneyItemAccountTextField.getText(), Double.parseDouble(cashRecordItemSumTextField.getText()), cashRecordItemCommentTextField.getText());
                moneyBLService.addItem(moneyLineItemVO);
                ((FinancialReceiptItemTableModel)cashRecordItemTable.getModel()).addRow(moneyLineItemVO);
            } catch (RemoteException ex) {
                Logger.getLogger(ReceiptUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            cashRecordItemNameTextField.setText("");
            cashRecordItemSumTextField.setText("");
            cashRecordItemCommentTextField.setText("");
            addCashRecordItemDialog.setVisible(false);
        }else{
            cashRecordItemSumHint.setText("请输入有效的数字");
            return;
        }
    }//GEN-LAST:event_addCashRecordItemEnsureButtonMousePressed

    private void addCashRecordItemCancelButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCashRecordItemCancelButtonMousePressed
            cashRecordItemNameTextField.setText("");
            cashRecordItemSumTextField.setText("");
            cashRecordItemSumHint.setText("");
            cashRecordItemCommentTextField.setText("");
            addCashRecordItemDialog.setVisible(false);
    }//GEN-LAST:event_addCashRecordItemCancelButtonMousePressed

    private void findTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_findTextFieldFocusGained
        if(findTextField.getText().equals("请输入单据编号")){
            findTextField.setText("");
            findTextField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_findTextFieldFocusGained

    private void findTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_findTextFieldFocusLost
        if(findTextField.getText().equals("")){
            findTextField.setText("请输入单据编号");
            findTextField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_findTextFieldFocusLost

    private void findAccountButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findAccountButtonMousePressed
        if(type != ReceiptType.CashRecord){
            
        }
    }//GEN-LAST:event_findAccountButtonMousePressed
    ReceiptType type = ReceiptType.Receive;
   
    
    public ArrayList getItemCol(){
        ArrayList returnList = new ArrayList();
        if(type != ReceiptType.CashRecord){
            returnList.add("条目名");
            
        }else{
            returnList.add("账户名");
        }
        returnList.add("金额");
        returnList.add("备注");
        return  returnList;
    }
    
    public Vector getMoneyCol(){
        Vector returnList = new Vector();
        returnList.add("单据编号");
        returnList.add("客户");
        returnList.add("操作员");
        returnList.add("总额");
        return returnList;
    }
    
    public Vector getCashRecordCol(){
        Vector returnList = new Vector();
        returnList.add("单据编号");
        returnList.add("操作员");
        returnList.add("银行帐户");
        returnList.add("总额");
        return returnList;
    }
    
    public ReceiptType getReceiptType() {
        return type;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CashRecordItemName;
    private javax.swing.JButton addCashRecordCancelButton;
    private javax.swing.JButton addCashRecordEnsureButton;
    private javax.swing.JButton addCashRecordItemCancelButton;
    private javax.swing.JDialog addCashRecordItemDialog;
    private javax.swing.JButton addCashRecordItemEnsureButton;
    private javax.swing.JDialog addCashRecordReceiptDialog;
    private javax.swing.JButton addMoneyCancelButton;
    private javax.swing.JButton addMoneyEnsureButton;
    private javax.swing.JButton addMoneyItemCancelButton;
    private javax.swing.JDialog addMoneyItemDialog;
    private javax.swing.JButton addMoneyItemEnsureButton;
    private javax.swing.JDialog addMoneyReceiptDialog;
    private javax.swing.JButton addReceiptButton;
    private javax.swing.JLabel cashRecordAccountHintLabel;
    private javax.swing.JTextField cashRecordAccountName;
    private javax.swing.JButton cashRecordAddItemButton;
    private javax.swing.JButton cashRecordDelItemButton;
    private javax.swing.JTextField cashRecordItemCommentTextField;
    private javax.swing.JTextField cashRecordItemNameTextField;
    private javax.swing.JLabel cashRecordItemSumHint;
    private javax.swing.JTextField cashRecordItemSumTextField;
    private javax.swing.JTable cashRecordItemTable;
    private javax.swing.JLabel cashRecordSerialNumberLabel;
    private javax.swing.JLabel cashRecordSumLabel;
    private javax.swing.JLabel clientLabel1;
    private javax.swing.JLabel clientNameHintLabel;
    private javax.swing.JLabel clientNameHintLabel1;
    private javax.swing.JButton findAccountButton;
    private javax.swing.JTextField findTextField;
    private javax.swing.JLabel functionLabel;
    private javax.swing.JLabel itemAccountTitile;
    private javax.swing.JLabel itemCommentTitile;
    private javax.swing.JLabel itemCommentTitile1;
    private javax.swing.JLabel itemSumTitile;
    private javax.swing.JLabel itemSumTitile1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton moneyAddItemButton;
    private javax.swing.JLabel moneyClientLabel;
    private javax.swing.JTextField moneyClientTextField;
    private javax.swing.JButton moneyDelItemButton;
    private javax.swing.JLabel moneyItemAccountHintLabel;
    private javax.swing.JTextField moneyItemAccountTextField;
    private javax.swing.JTextField moneyItemCommentTextField;
    private javax.swing.JLabel moneyItemSumHint;
    private javax.swing.JTextField moneyItemSumTextField;
    private javax.swing.JTable moneyItemTable;
    private javax.swing.JLabel moneySerialNumberLabel;
    private javax.swing.JLabel moneySumLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JTable receiptTabel;
    private javax.swing.JLabel title1Label;
    private javax.swing.JLabel title1Label1;
    private javax.swing.JComboBox typeComboBox;
    // End of variables declaration//GEN-END:variables

}
