/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demoui;

/**
 *
 * @author HCW
 */
public class SalesMainUI extends javax.swing.JPanel {

    /**
     * Creates new form salesManUI1
     */
    public SalesMainUI() {
        initComponents();
        salesmanCardPanel.setBounds(160, 65, 800, 600);
        add(salesmanCardPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salesman = new javax.swing.JLabel();
        clientManager = new javax.swing.JButton();
        importManager = new javax.swing.JButton();
        importReturn = new javax.swing.JButton();
        salesManager = new javax.swing.JButton();
        salesReturn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 687));
        setVerifyInputWhenFocusTarget(false);

        salesman.setFont(new java.awt.Font("楷体", 0, 36)); // NOI18N
        salesman.setText("进货销售人员");

        clientManager.setFont(new java.awt.Font("楷体", 0, 16)); // NOI18N
        clientManager.setText("客户管理");
        clientManager.setMaximumSize(new java.awt.Dimension(111, 35));
        clientManager.setMinimumSize(new java.awt.Dimension(111, 35));
        clientManager.setPreferredSize(new java.awt.Dimension(111, 35));
        clientManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientManagerActionPerformed(evt);
            }
        });

        importManager.setFont(new java.awt.Font("楷体", 0, 16)); // NOI18N
        importManager.setText("进货管理");
        importManager.setBorderPainted(false);
        importManager.setPreferredSize(new java.awt.Dimension(111, 35));
        importManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importManagerActionPerformed(evt);
            }
        });

        importReturn.setFont(new java.awt.Font("楷体", 0, 16)); // NOI18N
        importReturn.setText("进货退货");
        importReturn.setBorderPainted(false);
        importReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importReturnActionPerformed(evt);
            }
        });

        salesManager.setFont(new java.awt.Font("楷体", 0, 16)); // NOI18N
        salesManager.setText("销售管理");
        salesManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesManagerActionPerformed(evt);
            }
        });

        salesReturn.setFont(new java.awt.Font("楷体", 0, 16)); // NOI18N
        salesReturn.setText("销售退货");
        salesReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(434, 434, 434)
                .addComponent(salesman)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salesManager)
                    .addComponent(salesReturn)
                    .addComponent(importManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(importReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clientManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(941, 941, 941))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {clientManager, importManager, importReturn, salesManager, salesReturn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(salesman)
                .addGap(94, 94, 94)
                .addComponent(clientManager, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(importManager, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(importReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(salesManager)
                .addGap(40, 40, 40)
                .addComponent(salesReturn)
                .addGap(136, 136, 136))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {clientManager, importManager, importReturn, salesManager, salesReturn});

    }// </editor-fold>//GEN-END:initComponents

    private void salesReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesReturnActionPerformed
        // TODO add your handling code here:
        salesmanCardPanel.changeTosalesReturnUI();
        this.repaint();
    }//GEN-LAST:event_salesReturnActionPerformed

    private void salesManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesManagerActionPerformed
        // TODO add your handling code here:
        salesmanCardPanel.changeTosalesUI();
        this.repaint();
    }//GEN-LAST:event_salesManagerActionPerformed

    private void importReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importReturnActionPerformed
        // TODO add your handling code here:
        salesmanCardPanel.changeToimportReturnUI();
        this.repaint();
    }//GEN-LAST:event_importReturnActionPerformed

    private void clientManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientManagerActionPerformed
        // TODO add your handling code here:
        salesmanCardPanel.changeToclientUI();
        this.repaint();
    }//GEN-LAST:event_clientManagerActionPerformed

    private void importManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importManagerActionPerformed
        // TODO add your handling code here:
        salesmanCardPanel.changeToimportUI();
        this.repaint();
    }//GEN-LAST:event_importManagerActionPerformed

private SalesmanCardPanel salesmanCardPanel = new SalesmanCardPanel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clientManager;
    private javax.swing.JButton importManager;
    private javax.swing.JButton importReturn;
    private javax.swing.JButton salesManager;
    private javax.swing.JButton salesReturn;
    private javax.swing.JLabel salesman;
    // End of variables declaration//GEN-END:variables
}
