/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demoui;

import demoui.clientui.ClientUI;
import demoui.importui.ImportReturnUI;
import demoui.importui.ImportUI;
import demoui.salesui.SalesReturnUI;
import demoui.salesui.SalesUI;
import java.awt.CardLayout;
import javax.swing.BorderFactory;

/**
 *
 * @author HCW
 */
public class SalesmanCardPanel extends javax.swing.JPanel {

    /**
     * Creates new form salesmanCardPanel
     */
    public SalesmanCardPanel() {
        initComponents();
        myInitial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void myInitial() {
        this.setLayout(salesmanCardLayout);
        this.setBorder(BorderFactory.createEmptyBorder());
        add(salesReturnUI, "salesReturnUI");
        add(salesUI, "salesUI");
        add(clientUI, "clientUI");
        add(importUI, "importUI");
        add(importReturnUI, "importReturnUI");
        add(welcomeUI, "welcomeUI");
        salesmanCardLayout.show(this, "welcomeUI");
    }
    public void changeTosalesUI(){
        salesUI = new SalesUI();
        salesmanCardLayout.show(this, "salesUI");
    }
    public void changeTosalesReturnUI(){
        salesReturnUI = new SalesReturnUI();
        salesmanCardLayout.show(this, "salesReturnUI");
    }
    public void changeToclientUI(){
        clientUI = new ClientUI();
        salesmanCardLayout.show(this, "clientUI");
    }
    public void changeToimportUI(){
        importUI = new ImportUI();
        salesmanCardLayout.show(this, "importUI");
    }
    public void changeToimportReturnUI(){
        importReturnUI = new ImportReturnUI();
        salesmanCardLayout.show(this, "importReturnUI");
    }
    private CardLayout salesmanCardLayout = new CardLayout();
    
    private SalesUI salesUI = new SalesUI();
    private SalesReturnUI salesReturnUI = new SalesReturnUI();
    private ClientUI clientUI = new ClientUI();
    private ImportUI importUI = new ImportUI();
    private ImportReturnUI importReturnUI = new ImportReturnUI();
    private WelcomeUI welcomeUI = new WelcomeUI();
    
            
}
