/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demoui.clientui;

import businesslogicservice.clientblservice.ClientBLService;
import server.ClientStart;

/**
 *
 * @author HCW
 */
public class ClientUI extends javax.swing.JPanel {

    /**
     * Creates new form ClientUI
     */
    public ClientUI() {
        initComponents();
       // controller = ClientStart.getClientBLService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClientManagerLable = new javax.swing.JLabel();
        addClientButton = new javax.swing.JButton();
        deleteClientButton = new javax.swing.JButton();
        changeClientButton = new javax.swing.JButton();
        findClientButton = new javax.swing.JButton();
        clientListPanel = new demoui.clientui.ClientListPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));

        ClientManagerLable.setFont(new java.awt.Font("楷体", 0, 36)); // NOI18N
        ClientManagerLable.setText("客户管理");

        addClientButton.setText("添加客户");

        deleteClientButton.setText("删除客户");

        changeClientButton.setText("修改客户");

        findClientButton.setText("查找客户");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(ClientManagerLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(328, 328, 328))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(addClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(deleteClientButton)
                .addGap(122, 122, 122)
                .addComponent(changeClientButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(findClientButton)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(clientListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addClientButton, changeClientButton, deleteClientButton, findClientButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(ClientManagerLable, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteClientButton)
                    .addComponent(changeClientButton)
                    .addComponent(findClientButton))
                .addGap(12, 12, 12)
                .addComponent(clientListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addClientButton, changeClientButton, deleteClientButton, findClientButton});

    }// </editor-fold>//GEN-END:initComponents

    private ClientBLService controller;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClientManagerLable;
    private javax.swing.JButton addClientButton;
    private javax.swing.JButton changeClientButton;
    private demoui.clientui.ClientListPanel clientListPanel;
    private javax.swing.JButton deleteClientButton;
    private javax.swing.JButton findClientButton;
    // End of variables declaration//GEN-END:variables
}
